### ISSUE TITLE
[Feature] Connect to ssserver and then to a proxy

### ISSUE THREAD

**Issue by v1rtl** [zonyitoo/shadowsocks-proxy-plugin#1]
would be cool to be able to do the opposite process, where a server-side plugin would forward SOCKS5 traffic of ssserver onto another socks5/http proxy, like this:

```
┌────────────────┐         ┌────────────────┐        ┌───────────────┐
│                │         │                │        │               │
│                ┼─────────│ ssserver       │        │ socks5 proxy  │
│ sslocal        │         │                ┼────────│               │
│                │         │                │        │               │
└────────────────┘         └────────────────┘        └───────────────┘
```

**Comment by zonyitoo** [comment]
Then the payload data is SOCKS5, so both `sslocal` and `ssserver` don't need to know anything the target socks5 proxy.

For example, run `sslocal` in `tunnel` mode, and then set the `forward-addr` to the targeted socks5 proxy. SOCKS5 client set `sslocal`'s listen address as server.
